# -*- coding: utf-8 -*-
"""Car Market Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJQSyLT1xMh9TVCCtOirqpZY_cby5K6J
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset loading
df=pd.read_csv('/content/1776311302-P3-Car Market Trends Analysis with Car Dekho Data.csv')

# first five rows
df.head()

# last Five rows
df.tail()

# number of columns and shape
df.shape

# column Names
df.columns

# dataset information
df.info()

# Missing values check
df.isnull().sum()

# Duplicate rows check
df.duplicated().sum()

# statistical information
df.describe()

# selling price statistics
df['Selling_Price'].describe()

# Average selling price
df['Selling_Price'].mean()

"""Data Visualization"""

# 1.Present Price vs Selling Price
plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x='Present_Price',
    y='Selling_Price',
    color='royalblue',
    s=80,
    alpha=0.7
)

plt.title('Present Price vs Selling Price',
          fontsize=16, fontweight='bold')

plt.xlabel('Present Price', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

"""# Insight From This Graph
“The graph shows a positive relationship between Present Price and Selling Price. In general, cars with higher present prices tend to have higher selling prices.”
"""

# 2. Kms Driven vs Selling Price
plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x='Kms_Driven',
    y='Selling_Price',
    color='darkorange',
    s=80,
    alpha=0.7
)

plt.title('Kilometers Driven vs Selling Price',
          fontsize=16, fontweight='bold')

plt.xlabel('Kilometers Driven', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

"""Insight From This Graph

“The graph shows a generally negative relationship between Kilometers Driven and Selling Price. Cars with higher kilometers driven tend to have lower selling prices, although some variations and outliers are present.”
"""

# 3.Selling Price vs Fuel Type
plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x='Fuel_Type',
    y='Selling_Price',
    color='mediumseagreen'
)

plt.title('Selling Price by Fuel Type',
          fontsize=16, fontweight='bold')

plt.xlabel('Fuel Type', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()

plt.show()

"""Insight From This Graph

"Diesel cars generally have higher selling prices compared with Petrol and CNG cars in the dataset.”
"""

# 4. selling price by Transmission
plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x='Transmission',
    y='Selling_Price',
    color='mediumpurple'
)

plt.title('Selling Price by Transmission',
          fontsize=16, fontweight='bold')

plt.xlabel('Transmission Type', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()

plt.show()

"""# Insight From This Graph
“Automatic cars generally have higher selling prices than Manual cars in the dataset.”
"""

# 5.Selling Price by Seller Type
plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x='Seller_Type',
    y='Selling_Price',
    color='cornflowerblue'
)

plt.title('Selling Price by Seller Type',
          fontsize=16, fontweight='bold')

plt.xlabel('Seller Type', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()

plt.show()

"""# Insight From This Graph
“Cars sold by dealers generally have higher selling prices and greater price variation compared to cars sold by individual sellers. Individual sellers mostly sell cars at lower prices, with a few high-price outliers.”
"""

# 6. Car Age Vs Selling Price
current_year = 2026

df['Car_Age'] = current_year - df['Year']

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x='Car_Age',
    y='Selling_Price',
    color='crimson',
    s=80,
    alpha=0.7
)

plt.title('Car Age vs Selling Price',
          fontsize=16, fontweight='bold')

plt.xlabel('Car Age (Years)', fontsize=12)
plt.ylabel('Selling Price', fontsize=12)

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

"""# Insights From This Graph
“The selling price generally decreases as the age of the car increases. Older cars mostly have lower selling prices, while some high-priced outliers are observed among certain car ages.”
"""

# 7. Selling Price by Year
year_price = df.groupby('Year')['Selling_Price'].mean().reset_index()

plt.figure(figsize=(10, 6))

sns.lineplot(
    data=year_price,
    x='Year',
    y='Selling_Price',
    color='teal',
    marker='o',
    linewidth=2.5
)

plt.title('Average Selling Price by Year',
          fontsize=16, fontweight='bold')

plt.xlabel('Manufacturing Year', fontsize=12)
plt.ylabel('Average Selling Price', fontsize=12)

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()

"""# Insight From This Graph
Overall, average selling price shows an increasing trend over the years, especially after 2011, although there are some year-to-year fluctuations.
"""

# 8.Correlation Heatmap
plt.figure(figsize=(10, 7))

numeric_data = df.select_dtypes(include=np.number)

sns.heatmap(
    numeric_data.corr(),
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    linewidths=0.5
)

plt.title('Correlation Heatmap',
          fontsize=16, fontweight='bold')

plt.tight_layout()

plt.show()

"""# Insight From This Graph
Present Price is the most strongly correlated feature with Selling Price (0.88), while Kms Driven and Owner show very little correlation with Selling Price.
"""

# 9. Average Selling Price by year
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))

sns.barplot(
    data=df,
    x='Year',
    y='Selling_Price',
    estimator='mean',
    errorbar=None,
    color='steelblue'
)

plt.title('Average Selling Price by Year', fontsize=16, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Average Selling Price')
plt.xticks(rotation=45)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""# Insight From This Graph
The average selling price generally increases with the manufacturing year, indicating that newer cars tend to have higher selling prices in this dataset.
"""

# 10. Number of cars by year
plt.figure(figsize=(10, 5))

sns.countplot(
    data=df,
    x='Year',
    color='darkorange'
)

plt.title('Number of Cars by Manufacturing Year',
          fontsize=16, fontweight='bold')
plt.xlabel('Manufacturing Year')
plt.ylabel('Number of Cars')
plt.xticks(rotation=45)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""# Insight From This Graph
Most cars in the dataset are newer vehicles, with 2015 having the highest representation.
"""

# 11. present price distribution
plt.figure(figsize=(10, 6))

sns.histplot(
    data=df,
    x='Present_Price',
    bins=30,
    color='crimson',
    kde=True
)

plt.title('Distribution of Present Price',
          fontsize=16, fontweight='bold')
plt.xlabel('Present Price')
plt.ylabel('Number of Cars')

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""# Insight From This Graph
Most cars in the dataset are relatively low-priced, while expensive cars are rare.
"""

# 12. Selling Price Distribution
plt.figure(figsize=(10, 6))

sns.histplot(
    data=df,
    x='Selling_Price',
    bins=30,
    color='royalblue',
    kde=True
)

plt.title('Distribution of Selling Price',
          fontsize=16, fontweight='bold')
plt.xlabel('Selling Price')
plt.ylabel('Number of Cars')

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""# Insight From This Graph
The dataset mainly consists of cars sold at lower prices, while high-priced cars are relatively rare.
"""